version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: earnings-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  redisdata:
