module.exports = {
  apps: [
    {
      name: "earnings-table-web",
      script: "npm",
      args: "start",
      cwd: "./",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/web-error.log",
      out_file: "./logs/web-out.log",
      log_file: "./logs/web-combined.log",
      time: true,
    },
    {
      name: "earnings-watchdog",
      script: "npx",
      args: "tsx scripts/watchdog.ts",
      cwd: "./",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        WATCHDOG_MODE: "daemon",
        WATCHDOG_INTERVAL_MS: "300000", // 5 minutes
      },
      error_file: "./logs/watchdog-error.log",
      out_file: "./logs/watchdog-out.log",
      log_file: "./logs/watchdog-combined.log",
      time: true,
    },
    {
      name: "earnings-scheduler",
      script: "npx",
      args: "tsx scripts/cron-scheduler.ts",
      cwd: "./",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/scheduler-error.log",
      out_file: "./logs/scheduler-out.log",
      log_file: "./logs/scheduler-combined.log",
      time: true,
    },
  ],
};
