version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: earnings-postgres
    environment:
      POSTGRES_DB: earnings_table
      POSTGRES_USER: earnings_user
      POSTGRES_PASSWORD: earnings_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U earnings_user -d earnings_table" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: earnings-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: earnings-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://earnings_user:earnings_password@postgres:5432/earnings_table
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    # Resource limits to prevent memory issues
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  cron-worker:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: earnings-cron
    environment:
      - DATABASE_URL=postgresql://earnings_user:earnings_password@postgres:5432/earnings_table
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    # Resource limits for cron worker
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres_data:
  redis_data:
